### ISSUE TITLE
Mary's critiques of the proposal submission page

### ISSUE THREAD

**Issue by brianharvey** [snap-cloud/snapcon#35]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**

- [x] The heading that says "SnapCon account" should say "Make a SnapCon account" instead.  There's the tiny "already have" text in the corner to give you a clue, but only the fact that you have to type the password twice really makes it clear that this is a creation page rather than a login page.

- [x] If you click "Log in using Snap!" it leaves you in the forum, and if you then go back to snapcon.org it still asks you to make an account before submitting.

- [x] There's a hint about what each type of presentation means, but the language field comes in between the type field and that hint.

- [x] Speaking of the "Language" field, it only has one option, so what's the point?

- [x] The "Do you need anything special?" link really doesn't apply to an online, remote conference.

- [x] The "Create proposal" button is strangely named; people would expect "Submit proposal."  This sounds as if there's another page with more questions to fill out after pushing the button.

**Expected correct behavior:**

Not the above.

**Steps to reproduce:**

Click on the call for participation when not logged in.

**Other information:**

Pi and e are transcendental.

**Comment by cycomachead** [comment]
I think I've addressed all of these... the sign into forum thing is a bug that needs to be addressed with the forum... :/ Login through the forum is currently disabled.
