### ISSUE TITLE
Cleanup Title on Conference Materials Page

### ISSUE THREAD

**Issue by cycomachead** [snap-cloud/snapcon#76]
**I'm submitting a ..**
- [ ] Bug Report
- [X] Feature Request

**Current behavior:**
https://www.snapcon.org/admin/conferences/snapshot2020/commercials
Says "session" in the header
**Expected correct behavior:**
Should say "Conference" but the session pages should have the word session.

Actually, both pages should show the title of the conference/event/something else.

**Steps to reproduce:**

**Other information:**

**Comment by lzy-106** [comment]
![图片](https://user-images.githubusercontent.com/60304378/117098325-fa042100-ad22-11eb-9b90-b06af4a83508.png)

**Comment by cycomachead** [comment]
Thanks!!
